### ISSUE TITLE
Spend a few hours improving the candidate editing form

### ISSUE THREAD

**Issue by zarino** [mysociety/yournextmp-popit#130]
This is something @mhl and I wanted to do before Christmas. Maybe now's the time to prioritise it?

Improvements would include:

- [x] Make validation errors much harder to miss (https://github.com/mysociety/yournextmp-popit/issues/167)
- [ ] Contextual help on where to find social media handles and websites (https://github.com/mysociety/yournextmp-popit/issues/120)
- [x] LinkedIn field (https://github.com/mysociety/yournextmp-popit/issues/50)
- [x] Make it clear that Twitter field should exclude the "@" (https://github.com/mysociety/yournextmp-popit/issues/131) 
- [x] Clearer structure for the whole form, so it's easier to find, say, all the social media inputs, or all the websites.
- [x] Bring the design of the "Source URL" input in line with the ones on the Constituency page (inside a yellow box at least, even if we don't want to have it shown/hidden by javascript)

From what I can tell, apart from adding a LinkedIn field to the candidate model, this is mostly front-end work, and would only take a few hours. (Yes, that's me volunteering to do it, if you guys think it's a worthwhile investment of my time.)

**Comment by mhl** [comment]
I'm enthusiastic about this - my only question is whether this is higher priority than redesigning the person page (view rather than edit) since those are much more prominent, and getting quite a lot of hits via Google now.

**Comment by zarino** [comment]
Good point @mhl – hence why I leave the prioritisation to people more qualified than I ;-)

**Comment by mhl** [comment]
Something else that should be part of this work is making sure that the validation errors are really clear: https://github.com/mysociety/yournextmp-popit/issues/167

**Comment by zarino** [comment]
> Something else that should be part of this work is making sure that the validation errors are really clear: #167

@mhl – Good spot. I've added it to the list at the top of the thread.

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/yournextmp-popit/pull/223

**Comment by mhl** [comment]
This is now way better, thanks to @zarino for all his work on that
